use e_commerce;
--Which product categories contribute the most revenue, and should receive more marketing investment?
select sum(od.price+od.freight_value)as revenue,o.product_category_name
from olist_order_items_dataset od inner join olist_products_dataset o
on od.product_id =o.product_id
group by o.product_category_name
order by revenue desc

--Which product categories generate high sales volume but low revenue?
select count(*)as sale_vol,sum(od.price+od.freight_value)as revenue,
o.product_category_name
from olist_order_items_dataset od inner join olist_products_dataset o
on od.product_id =o.product_id
group by o.product_category_name
order by sale_vol desc
--INTERPRETATION--
/* cama_mesa_banho recorded the highest sales volume among all categories,
indicating strong customer demand. beleza_saude generated fewer sales but remained among the top-performing categories.
Further analysis is required to determine whether these categories also generate high revenue and profitability.
*/

--What are the monthly revenue trends, and are there signs of seasonality?
select sum(od.price+od.freight_value)as revenue,
FORMAT(o.order_purchase_timestamp, 'yyyy-MM') AS MonthYear
from olist_order_items_dataset od inner join olist_orders_dataset1 o
on od.order_id =o.order_id
group by FORMAT(o.order_purchase_timestamp, 'yyyy-MM') 
order by monthyear
--INTERPRETATION--
/*Revenue exhibited strong growth throughout 2017, increasing from approximately 137K in January 2017 to a peak of 1.18M in November 2017. 
Revenue remained consistently high throughout 2018, generally exceeding 1M per month. 
A significant spike in November 2017 suggests possible seasonal effects, promotional campaigns,
or holiday-related purchasing behavior.
*/
--Which states generate the highest revenue for the business?
select c.customer_state,sum(od.price+od.freight_value)as revenue
from olist_customers_dataset c inner join olist_orders_dataset1 o
on c.customer_id=o.customer_id
inner join olist_order_items_dataset od
on o.order_id=od.order_id
group by c.customer_state
order by revenue desc
--INTERPRETATION
/*Revenue is highly concentrated in a few states, 
with São Paulo contributing substantially more revenue than any other region. 
This indicates that the company's sales activity is strongest in the southeastern region of Brazil.
*/

--Who are the top 10% of customers contributing the most revenue?
WITH customer_revenue AS
(   SELECT
        c.customer_id,
        SUM(od.price + od.freight_value) AS revenue
    FROM olist_customers_dataset c
    INNER JOIN olist_orders_dataset1 o
        ON c.customer_id = o.customer_id
    INNER JOIN olist_order_items_dataset od
        ON o.order_id = od.order_id
    GROUP BY c.customer_id
),
customer_segments AS
( SELECT
        customer_id,
        revenue,
        NTILE(10) OVER (ORDER BY revenue DESC) AS revenue_decile
    FROM customer_revenue)
SELECT *
FROM customer_segments
WHERE revenue_decile = 1
ORDER BY revenue DESC;
--INTERPRETATION
/*The top 10% of customers generated substantially higher revenue than the remaining customer base.
This indicates that a relatively small segment of customers contributes a disproportionate share of total business revenue,
highlighting the importance of retaining and engaging high-value customers.
*/

--What percentage of revenue comes from repeat customers versus one-time customers?
WITH customer_orders AS
(
    SELECT
        c.customer_id,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(od.price + od.freight_value) AS revenue
    FROM olist_customers_dataset c
    INNER JOIN olist_orders_dataset1 o
        ON c.customer_id = o.customer_id
    INNER JOIN olist_order_items_dataset od
        ON o.order_id = od.order_id
    GROUP BY c.customer_id
),
customer_type AS
(
    SELECT
        CASE
            WHEN total_orders = 1 THEN 'One-Time Customer'
            ELSE 'Repeat Customer'
        END AS customer_segment,
        revenue
    FROM customer_orders)
SELECT
    customer_segment,
    SUM(revenue) AS total_revenue,
    ROUND(
        100.0 * SUM(revenue) /
        SUM(SUM(revenue)) OVER (),
        2
    ) AS revenue_percentage
FROM customer_type
GROUP BY customer_segment;
--INTERPRETATION
/*Analysis based on customer_id indicates that 100% of revenue was generated by one-time customers.
However, this result is likely influenced by the dataset's customer identification structure,
where each purchase may be assigned a unique customer_id. 
Further validation using customer_unique_id is required to accurately distinguish repeat customers from one-time customers.
*/
-- Which customer segments should be targeted for retention campaigns?
WITH customer_revenue AS
(
    SELECT
        c.customer_id,
        SUM(od.price + od.freight_value) AS revenue
    FROM olist_customers_dataset c
    INNER JOIN olist_orders_dataset1 o
        ON c.customer_id = o.customer_id
    INNER JOIN olist_order_items_dataset od
        ON o.order_id = od.order_id
    GROUP BY c.customer_id
),
customer_segments AS
(
    SELECT
        customer_id,
        revenue,
        NTILE(4) OVER (ORDER BY revenue DESC) AS segment
    FROM customer_revenue
)

SELECT
    CASE
        WHEN segment = 1 THEN 'High Value'
        WHEN segment IN (2,3) THEN 'Medium Value'
        WHEN segment = 4 THEN 'Low Value'
    END AS customer_segment,
    COUNT(*) AS customers,
    SUM(revenue) AS total_revenue,
    ROUND(
        100.0 * SUM(revenue) / SUM(SUM(revenue)) OVER (),
        2
    ) AS revenue_percentage
FROM customer_segments
GROUP BY
    CASE
        WHEN segment = 1 THEN 'High Value'
        WHEN segment IN (2,3) THEN 'Medium Value'
        WHEN segment = 4 THEN 'Low Value'
    END
ORDER BY total_revenue DESC;

--INTERPRETATION
/*Revenue is heavily concentrated among High Value customers.
Although they represent a relatively small portion of the customer base, 
they generate the majority of the company's revenue. 
This indicates that customer value is unevenly distributed and that retaining High Value customers is critical to sustaining business performance.
*/

--Which regions have high customer acquisition but low repeat purchases?
WITH customer_orders AS
(
    SELECT
        c.customer_unique_id,
        c.customer_state,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM olist_customers_dataset c
    INNER JOIN olist_orders_dataset1 o
        ON c.customer_id = o.customer_id
    GROUP BY
        c.customer_unique_id,
        c.customer_state
),
state_metrics AS
(
    SELECT
        customer_state,
        COUNT(*) AS total_customers,
        SUM(
            CASE
                WHEN total_orders > 1 THEN 1
                ELSE 0
            END
        ) AS repeat_customers
    FROM customer_orders
    GROUP BY customer_state
)

SELECT
    customer_state,
    total_customers,
    repeat_customers,
    ROUND(
        100.0 * repeat_customers / total_customers,
        2
    ) AS repeat_purchase_rate
FROM state_metrics
ORDER BY total_customers DESC,
         repeat_purchase_rate ASC;
--INTERPRETATION
/*While São Paulo contributes the largest customer base (40,302 customers), only 3.22% of customers make repeat purchases. 
Similar patterns are observed across other major states, suggesting that customer acquisition is strong but retention remains a challenge. 
Improving customer loyalty in these high-volume regions could generate substantial long-term revenue growth without increasing acquisition costs.
*/

--What is the average time between purchases for repeat customers?
WITH customer_orders AS
(
    SELECT
        c.customer_unique_id,
        o.order_purchase_timestamp
    FROM olist_customers_dataset c
    INNER JOIN olist_orders_dataset1 o
        ON c.customer_id = o.customer_id
),

purchase_gaps AS
(
    SELECT
        customer_unique_id,
        order_purchase_timestamp,
        LAG(order_purchase_timestamp) OVER
        (
            PARTITION BY customer_unique_id
            ORDER BY order_purchase_timestamp
        ) AS previous_purchase
    FROM customer_orders
)

SELECT
    AVG(
        DATEDIFF(
            DAY,
            previous_purchase,
            order_purchase_timestamp
        ) * 1.0
    ) AS avg_days_between_purchases
FROM purchase_gaps
WHERE previous_purchase IS NOT NULL;

--INTERPRETATION
/*Analysis of repeat purchasing behavior revealed that customers take an average of 78.23 days to place their next order.
This indicates a repurchase cycle of roughly two and a half months. 
Understanding this purchasing cadence can help the business optimize the timing of retention campaigns and promotional offers to increase repeat purchase rates.
*/

--Which sellers generate the highest revenue but receive poor customer ratings?
WITH seller_performance AS
(
    SELECT
        oi.seller_id,
        SUM(oi.price + oi.freight_value) AS revenue,
        AVG(CAST(orv.review_score AS DECIMAL(10,2))) AS avg_rating
    FROM olist_order_items_dataset oi
    INNER JOIN olist_order_reviews_dataset1 orv
        ON oi.order_id = orv.order_id
    GROUP BY oi.seller_id)
SELECT *
FROM seller_performance
ORDER BY revenue DESC;

--INTERPRETATION
/*The average seller rating across the platform is 3.97. 
However, some high-revenue sellers perform below this benchmark. 
For example, seller 7c67e1448b00f6e969d365cea6b010ab generated approximately 239.6K in revenue while maintaining an average rating of only 3.35.
This suggests that substantial revenue is being generated despite lower customer satisfaction levels.
*/

--Which sellers should be rewarded based on sales and customer satisfaction?
WITH seller_performance AS
(
    SELECT
        oi.seller_id,
        SUM(oi.price + oi.freight_value) AS revenue,
        AVG(CAST(orv.review_score AS DECIMAL(10,2))) AS avg_rating
    FROM olist_order_items_dataset oi
    INNER JOIN olist_order_reviews_dataset1 orv
        ON oi.order_id = orv.order_id
    GROUP BY oi.seller_id
),
seller_segments AS
(
    SELECT
        seller_id,
        revenue,
        avg_rating,
        NTILE(4) OVER (ORDER BY revenue DESC) AS revenue_quartile
    FROM seller_performance
)
SELECT
    seller_id,
    revenue,
    avg_rating
FROM seller_segments
WHERE revenue_quartile = 1
  AND avg_rating > 3.97
ORDER BY revenue DESC;

--INTERPRETATION
/*A group of sellers demonstrated exceptional performance by achieving both high revenue and above-average customer ratings.
These sellers are not only contributing significantly to overall sales but are also maintaining strong customer satisfaction levels. 
Their ability to balance revenue generation with positive customer experiences makes them valuable partners for the business.
*/

--Which sellers have declining sales performance over time?
WITH monthly_seller_sales AS
(
    SELECT
        oi.seller_id,
        FORMAT(o.order_purchase_timestamp,'yyyy-MM') AS sales_month,
        SUM(oi.price + oi.freight_value) AS revenue
    FROM olist_order_items_dataset oi
    INNER JOIN olist_orders_dataset1 o
        ON oi.order_id = o.order_id
    GROUP BY
        oi.seller_id,
        FORMAT(o.order_purchase_timestamp,'yyyy-MM')
),

seller_trend AS
(
    SELECT
        seller_id,
        sales_month,
        revenue,
        LAG(revenue) OVER
        (
            PARTITION BY seller_id
            ORDER BY sales_month
        ) AS previous_revenue
    FROM monthly_seller_sales
)
SELECT *
FROM seller_trend
WHERE revenue < previous_revenue
ORDER BY seller_id,sales_month;

--INTERPRETATION
/*Analysis of monthly seller revenue identified several sellers with declining sales performance over time. 
The decline suggests potential challenges related to market demand, competition, inventory availability, or customer engagement.
Sellers experiencing the largest revenue contractions should be prioritized for further investigation to prevent future revenue loss and improve marketplace performance.
*/

--Which seller locations contribute the most to overall business revenue?
SELECT
    s.seller_state,
    SUM(oi.price + oi.freight_value) AS revenue
FROM olist_sellers_dataset s
INNER JOIN olist_order_items_dataset oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_state
ORDER BY revenue DESC;

--INTERPRETATION
/*Seller revenue is highly concentrated in a few key states, 
particularly São Paulo (SP), which significantly outperforms all other regions in revenue generation. 
This indicates that SP is the marketplace's strongest seller hub and plays a critical role in overall business performance.
*/

--Which states experience the longest delivery delays?
SELECT
    c.customer_state,
    AVG(
        DATEDIFF(
            DAY,
            o.order_estimated_delivery_date,
            o.order_delivered_customer_date
        ) * 1.0
    ) AS avg_delivery_delay
FROM olist_orders_dataset1 o
INNER JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_delay DESC;

--INTERPRETATION
/*The marketplace is consistently outperforming its promised delivery timelines across all states.
Customers receive their orders approximately 11–21 days earlier than expected on average.
States such as MS and SP have the smallest lead times (around 11 days early), while states such as AC and RO receive orders nearly 20 days
before the estimated delivery date.
*/

--What percentage of orders are delivered later than promised?
SELECT
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN order_delivered_customer_date > order_estimated_delivery_date
                THEN 1
                ELSE 0
            END
        )
        / COUNT(*),
        2
    ) AS late_delivery_percentage
FROM olist_orders_dataset1
WHERE order_delivered_customer_date IS NOT NULL;
--INTERPRETATION
/*The business demonstrates strong delivery performance, with the vast majority of orders
reaching customers on or before the estimated delivery date. Late deliveries affect only a small portion of orders, 
suggesting that the logistics and fulfillment processes are generally reliable.
*/

--Which sellers are responsible for the highest number of delayed deliveries?
SELECT TOP 10
    oi.seller_id,
    COUNT(*) AS delayed_orders
FROM olist_order_items_dataset oi
INNER JOIN olist_orders_dataset1 o
    ON oi.order_id = o.order_id
WHERE o.order_delivered_customer_date >
      o.order_estimated_delivery_date
GROUP BY oi.seller_id
ORDER BY delayed_orders DESC;


WITH seller_delays AS
(
    SELECT
        oi.seller_id,
        COUNT(*) AS total_orders,
        SUM(
            CASE
                WHEN o.order_delivered_customer_date >
                     o.order_estimated_delivery_date
                THEN 1
                ELSE 0
            END
        ) AS delayed_orders
    FROM olist_order_items_dataset oi
    INNER JOIN olist_orders_dataset1 o
        ON oi.order_id = o.order_id
    GROUP BY oi.seller_id
)
SELECT
    seller_id,
    total_orders,
    delayed_orders,
    ROUND(
        100.0 * delayed_orders / total_orders,
        2
    ) AS delay_percentage
FROM seller_delays
WHERE delayed_orders > 0
ORDER BY delayed_orders DESC;

--INTERPRETATION
/* While some sellers contribute a large number of delayed deliveries due to their high order volume,
others exhibit significantly higher delay rates. Sellers with high delay percentages should be prioritized for 
operational review, as they pose a greater risk to customer satisfaction and service quality.
*/

--How does delivery time affect customer satisfaction?

WITH delivery_analysis AS
(
    SELECT
        CASE
            WHEN DATEDIFF(DAY, o.order_purchase_timestamp,
                          o.order_delivered_customer_date) <= 7
                THEN '0-7 Days'

            WHEN DATEDIFF(DAY, o.order_purchase_timestamp,
                          o.order_delivered_customer_date) <= 14
                THEN '8-14 Days'

            WHEN DATEDIFF(DAY, o.order_purchase_timestamp,
                          o.order_delivered_customer_date) <= 21
                THEN '15-21 Days'

            ELSE '21+ Days'
        END AS delivery_bucket,
        r.review_score
    FROM olist_orders_dataset1 o
    INNER JOIN olist_order_reviews_dataset1 r
        ON o.order_id = r.order_id
    WHERE o.order_delivered_customer_date IS NOT NULL
)
SELECT
    delivery_bucket,
    AVG(CAST(review_score AS FLOAT)) AS avg_rating,
    COUNT(*) AS orders
FROM delivery_analysis
GROUP BY delivery_bucket
ORDER BY delivery_bucket;

--INTERPRETATION
/*Customer satisfaction is strongly influenced by delivery speed. Orders delivered within 7 days 
receive the highest average rating (4.41), while orders taking more than 21 days receive a significantly lower average rating (3.06). 
This indicates that customers value fast delivery and become less satisfied as delivery times increase.
*/

--Which product categories generate high revenue but consistently low review scores?
WITH category_performance AS
(
    SELECT
        p.product_category_name,
        SUM(oi.price + oi.freight_value) AS revenue,
        AVG(CAST(r.review_score AS FLOAT)) AS avg_rating
    FROM olist_products_dataset p
    INNER JOIN olist_order_items_dataset oi
        ON p.product_id = oi.product_id
    INNER JOIN olist_orders_dataset1 o
        ON oi.order_id = o.order_id
    INNER JOIN olist_order_reviews_dataset1 r
        ON o.order_id = r.order_id
    GROUP BY p.product_category_name
)
SELECT *
FROM category_performance
WHERE avg_rating < 4
ORDER BY revenue DESC;

--INTERPRETATION
/*These categories are commercially successful and attract substantial customer demand, 
but customer satisfaction does not match their revenue performance. This suggests potential issues related to 
product quality, delivery experience, product expectations, packaging, or after-sales service.
*/

--Which products should be investigated due to poor ratings despite strong sales?
SELECT
    p.product_id,
    p.product_category_name,
    SUM(oi.price + oi.freight_value) AS revenue,
    AVG(CAST(r.review_score AS FLOAT)) AS avg_rating
FROM olist_products_dataset p
INNER JOIN olist_order_items_dataset oi
    ON p.product_id = oi.product_id
INNER JOIN olist_order_reviews_dataset1 r
    ON oi.order_id = r.order_id
GROUP BY
    p.product_id,
    p.product_category_name
HAVING
    SUM(oi.price + oi.freight_value) > 10000
    AND AVG(CAST(r.review_score AS FLOAT)) < 4
ORDER BY revenue DESC;

--INTERPRETATION
/*These products continue to attract sales but consistently fail to meet customer expectations. 
For example, product fd0065af7f09af4b82a0ca8f3eed1852 generated over 22K in revenue while receiving an average rating
of only 1.18, indicating severe customer dissatisfaction. Similar patterns are observed in several automotive and telephony products.
*/
